# NumPy Indexing and Selection


In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
#Get a value at an index
arr[8]

8

In [5]:
# We can also assign -ve index (counts from the back)
arr[0], arr[4], arr[-1]

(0, 4, 10)

In [6]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [7]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
# Use negatives to count from the back.
arr[-4:]

array([ 7,  8,  9, 10])

---
A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [10]:
arr[-5::-2]

array([6, 4, 2, 0])

## Broadcasting


**Broadcasting helps in performing element wise operations on arrays of different dimensions.**

**The smaller array is broadcast to the size of the larger array so that they have compatible shapes.**

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [11]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
# Add a row to a matrix
mat = np.array([[1,2,3], [9,8,7]])
arr = np.array([1,1,1])

# On adding the two, arr will get broadcasted and will get added as a matrix with both rows same as [1,1,1]
mat + arr

array([[ 2,  3,  4],
       [10,  9,  8]])

In [13]:
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

**Now note the changes also occur in our original array!**

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

**Data is not copied, it's a view of the original array! This avoids memory problems!**

## Copying Array

Be careful with copying and modifying arrays in NumPy!


`arr_copy` is a slice of `arr`

**Here r and r2 point to the same array**

In [17]:
arr = np.arange(10)
print(arr) 

arr_copy = arr[: 5]      # Here arr_copy and arr points to the same array
print(arr_copy)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [18]:
# Showing that arr and arr_copy points to the same array

arr_copy[:] = 0

print(arr)

[0 0 0 0 0 5 6 7 8 9]


On changing arr_copy elements, we can see it those elements also got changed in the original array

------
To avoid this, use `arr.copy` to create a copy that will not affect the original array

**To make arr_copy and arr point to different arrays use copy() method**

In [19]:
arr = np.arange(10)

#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# Showing that arr and arr_copy points to the same array

arr_copy[:] = 0

print(arr)      # now we can see that changing arr_copy elements have no effect on arr elements

[0 1 2 3 4 5 6 7 8 9]


## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [21]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [23]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [24]:
# Getting individual element value
arr_2d[1,0]

20

In [25]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [26]:
#Shape bottom row
arr_2d[-1]

array([35, 40, 45])

In [27]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [28]:
arr_2d[:2, :-1]

array([[ 5, 10],
       [20, 25]])

---
This is a slice of the last row, and only every other element.

In [29]:
arr_2d[-1, ::2]

array([35, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [30]:
#Set up matrix
arr2d = np.zeros((10,10))

In [31]:
#Length of array
arr_length = arr2d.shape[1]

In [32]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [33]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [34]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:


## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [35]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [37]:
bool_arr = arr > 4

In [38]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [39]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
x = 2
arr[arr > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[arr > 5] = 10

arr

array([ 1,  2,  3,  4,  5, 10, 10, 10, 10, 10])

## Compare Arrays

We can also use comparison operators to compare complete arrays with one another

In [43]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

In [44]:
# We can compare complete arrays of equal size element wise
arr1 > arr2

array([[False, False],
       [False, False]])

In [45]:
# We can compare elements of an array with a given value
arr1 == 2

array([[False,  True],
       [False, False]])