# NumPy Operations

## Arithmetic

Numpy arrays allow us to directly apply a range of operations such as addition, subtraction etc. The operators are overloaded in the library which makes the process possible. The operations occur on an element by element basis.

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

**Numpy performs element wise operations**

In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 8, 9, 10])

In [2]:
x + y

array([ 7,  9, 11, 13, 15])

In [3]:
x - y

array([-5, -5, -5, -5, -5])

In [4]:
x * y

array([ 6, 14, 24, 36, 50])

In [5]:
x / y

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
x ** 2

array([ 1,  4,  9, 16, 25])

In [9]:
arr = np.array([0, 1, 2, 3, 4, 5])

In [10]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

/home/abhishek/.local/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.])

In [11]:
# Also warning, but not an error instead infinity
1/arr

/home/abhishek/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       ])

In [12]:
# Also warning, but not an error instead -infinity
-1/arr

/home/abhishek/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       -inf, -1.        , -0.5       , -0.33333333, -0.25      ,
       -0.2       ])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations we can use to perform the operation across the array. 

In [13]:
arr = np.arange(10)

In [14]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [15]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [16]:
np.max(arr) #same as arr.max()

9

In [17]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [18]:
np.log(arr)

/home/abhishek/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Vector and Matrix Operations

In [19]:
matrix1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix2 = np.array([[1,1,1], [0,0,0], [1,1,1]])

---
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [20]:
# Dot operator
np.dot(matrix1, matrix2)

array([[ 4,  4,  4],
       [10, 10, 10],
       [16, 16, 16]])

In [21]:
# Cross operator
np.cross(matrix1, matrix2)

array([[-1,  2, -1],
       [ 0,  0,  0],
       [-1,  2, -1]])

In [22]:
# Outer operator
np.outer(matrix1, matrix2)

array([[1, 1, 1, 0, 0, 0, 1, 1, 1],
       [2, 2, 2, 0, 0, 0, 2, 2, 2],
       [3, 3, 3, 0, 0, 0, 3, 3, 3],
       [4, 4, 4, 0, 0, 0, 4, 4, 4],
       [5, 5, 5, 0, 0, 0, 5, 5, 5],
       [6, 6, 6, 0, 0, 0, 6, 6, 6],
       [7, 7, 7, 0, 0, 0, 7, 7, 7],
       [8, 8, 8, 0, 0, 0, 8, 8, 8],
       [9, 9, 9, 0, 0, 0, 9, 9, 9]])

In [23]:
# Inner operator
np.inner(matrix1, matrix2)

array([[ 6,  0,  6],
       [15,  0, 15],
       [24,  0, 24]])